################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
CPP_UPPER_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
CC_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
CXX_DEPS := 
SREC := 
JMP_DEPS := 
CXX_UPPER_DEPS := 
P_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
MAP := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/board/ra6e1_voice \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_ioport \
ra/fsp/src/r_sci_uart \
ra_gen \
src/examples/hello_world \
src \
src/tensorflow/lite/c \
src/tensorflow/lite/core/api \
src/tensorflow/lite/kernels/internal \
src/tensorflow/lite/kernels/internal/reference \
src/tensorflow/lite/kernels \
src/tensorflow/lite/micro/RA6E1 \
src/tensorflow/lite/micro \
src/tensorflow/lite/micro/arena_allocator \
src/tensorflow/lite/micro/kernels \
src/tensorflow/lite/micro/memory_planner \
src/tensorflow/lite/schema \
src/third_party/kissfft \
src/third_party/kissfft/tools \

